### ISSUE TITLE
Incentivize longer staking

### ISSUE THREAD

**Issue by pajeon** [cogitoprotocol/gcoin#8]
It would be desirable to incentivize longer staking by offering higher rewards. This can be be for both GCOIN and CGV.

* Users would specify a duration when staking. Users may not withdraw their stake before that duration ends
* Assume max duration of 4 years, min 6 months (params can be adjusted)
* A rewards multiplier is determined by the duration. This can be proportionally linear to duration, eg. 3.5 yrs = `3.5 * rewardsRate`
* Alternatively, we can have tiers of rewards, eg. 0-1 yr = `1 * rewardsRate`, 1-2 yr = `2 * rewardsRate`, etc.

**Comment by TonyCryptoZ** [comment]
Make sense, maybe implement the linear one first and some helper function for display too

**Comment by TonyCryptoZ** [comment]
i think the withdraw(0) part is a little tricky, might need to think about the design. Reason is, we need to track (recalculate) how much user already claimed rewards etc. 

Reward rate is pre-determined and not re-adjusted. On time T, reward rate is 20%, on time T+2, we decided to ramp down to 10%, the user who stake at time T should still have 20%. 

Can this user withdraw the reward prior to the staking period? Can this user only withdraw some fund but not withdraw all? After the staking period can user withdraw only reward? 

If user withdraw only reward, maybe we can reset the stake timestamp to reflect those reward has been withdrew. Or else we need to record how much user withdraw as a separate variable and eventually reflect that user couldn't withdraw more than they earn.  @pajeon

**Comment by TonyCryptoZ** [comment]
Each user only has one stake -> i think this may not work, since they should be able to deposit multiple times, with different duration and rate? 

Upon unlock, they can withdraw between 0 and all of their stake, which also claims all rewards. Leftover stake continues to accrue rewards at the previous rate.  -> i think this is doable, we can pick one : 
1. need additional parameters to record down their withdraw reward 
2. Or we reset the start time of the deposit, after user withdraw the reward. And re-accure all the reward. I guess a bunch of security check need to change according to this.

**Comment by pajeon** [comment]
> Each user only has one stake -> i think this may not work, since they should be able to deposit multiple times, with different duration and rate?

What if their latest deposit just overrides the duration/rate for the entire amount?

**Comment by TonyCryptoZ** [comment]
Emm I think maybe better to reset the timer/start date etc, add a flag of this is no longer needs to fullfil min staking time, and pop it out and re-enter a new one. The reason is, we may want to put some promotion at the beginning so the rate is high, and later on rate might be lower, and the new amount overwrite the old one kinda prevent user to deposit moreOn Jun 10, 2023, at 8:16 AM, pajeon ***@***.***> wrote:﻿

Each user only has one stake -> i think this may not work, since they should be able to deposit multiple times, with different duration and rate?

What if their latest deposit just overrides the duration/rate for the entire amount?

**Comment by TonyCryptoZ** [comment]
Added functionality for this
